TheGrizF/s25-Iron

app/static/css/taste_profile.css

Optimized taste_profile.css to be a little less bulky

Optimized taste_profile.css

---

app/templates/dishMatches.html
app/templates/profile.html
backend/__init__.py
backend/routes/profile_routes.py
backend/utils.py

created a method to get dish recommendations in backend.utils
logic for recommendations is based on buddy matches, reviews, cuisine type for now.
implemented an api route for the call as well and display through the user profile page.
api should be usable and adjustable for daily dish as well as dish recommendation page.

30 logic for dish recommendations

---

app/templates/TasteBuds.html

Feel free to look in TasteBuds.html

Added 3 more friends to Buddies Selection

---

app/templates/TasteBuds.html

Feel free to look in TasteBuddies.html

Added more friends to Buddies list

---

app/templates/TasteBuds.html

All these changes are in the TasteBuds.html file

Added more friends and a comment if more friends are needed

---

app/static/css/style.css
app/static/css/taste_profile.css
app/static/js/taste_profile.js
app/templates/tasteProfile.html
app/templates/tasteProfile10.html
app/templates/tasteProfile11.html
app/templates/tasteProfile2.html
app/templates/tasteProfile3.html
app/templates/tasteProfile4.html
app/templates/tasteProfile5.html
app/templates/tasteProfile6.html
app/templates/tasteProfile7.html
app/templates/tasteProfile8.html
app/templates/tasteProfile9.html
app/templates/taste_profile_base.html
backend/routes/profile_routes.py

Added "done" and "continue" buttons to each step of taste profile builder.
Cleaned up "add other allergies" feild and button. 
Added progress bar to top of each step's container.

31 add exit button from taste profile builder and added a progress bar 

---

app/templates/profile.html
app/templates/user.html
backend/routes/profile_routes.py

I optimized profile.html for mobile view. added "taste profile" button, and showing the first several taste matches and dish recommendations on the profile page. Also created a user.html page to show other user's profiles (just basic for now - will do more work on that later) because it makes sense that the user should be able to click on a user's name.

cleaned up profile.html. added user.html to show other profiles

---

app/static/css/TasteBuds.css
app/static/css/groupMatch.css
app/static/js/toggleBuddies.js
app/templates/TasteBuds.html
app/templates/groupMatch.html
backend/routes/daily_dish_routes.py

17 modify UI for friendsgroup page

---

app/static/css/dailyDish.css
app/templates/dailyDish.html

Made entire cards clickable (to their respective dishes), while also keeping the restaraunt links clickable. Used z-indexes to handle that.

71 make cards in live feed clickable

---

app/templates/dailyDish.html
backend/routes/daily_dish_routes.py
backend/utils.py

Live updates now show on daily dish
Time stamp changed from general to relative since update was posted

56 update daily dish   live updates from restaurants

---

app/static/css/style.css
app/templates/base.html

Now the UI bar at the bottom of the page "highlights" an icon if the user is on that page

added highlight feature to bottom navbar

---

app/static/css/TasteBuds.css
app/static/css/dish_detail.css
app/static/css/restaurant_detail.css
app/static/css/review.css
app/static/css/style.css
app/templates/TasteBuds.html
app/templates/dish_detail.html
app/templates/review.html
app/templates/user.html
app/templates/userSearchResult.html
backend/routes/daily_dish_routes.py
backend/routes/dish_routes.py
backend/utils.py

Reviews save rating and content, the rest of the data is ghost for now and will consider if/how to connect later during polish phase

63 connect review to dish detail page

---

app/templates/TasteBuds.html
app/templates/base.html

made highlights on navbar persistent for subpages

made highlights on navbar persistent for subpages

---

app/static/css/dailyDish.css
app/static/css/restaurant_detail.css
app/templates/dailyDish.html
app/templates/profile.html
app/templates/restaurant_detail.html
app/templates/user.html
backend/routes/auth_routes.py
backend/routes/daily_dish_routes.py
backend/routes/profile_routes.py
backend/utils.py
database/databaseTestData/friends.csv
database/models/user.py

Changes I made:
-Tastebuddies on profile link to that user's profile
-moved live updates input box above restaurant hours
-moved live updates above restaurant about section
-follow and unfollow button
-when someone follows appears in the daily dish till the user dismisses the notification (This was oddly harder than it should of been)

84 add following notification to daily dish

---

app/templates/dailyDish.html
backend/routes/daily_dish_routes.py

I have no idea what I've done but this will fix it

fixed flash message issue and page refreshing

---

app/static/css/taste_profile.css
app/templates/addUser.html
backend/routes/auth_routes.py
backend/routes/profile_routes.py
database/models/taste_profiles.py

fixed up icon arrangement in user setup

83 frontend for user account setup profile icons

---

app/static/css/reviewedDishes.css
app/static/css/savedDishes.css
app/static/css/style.css
app/templates/profile.html
app/templates/reviewedDishes.html
app/templates/savedDishes.html
backend/routes/profile_routes.py

Changed profile.html to have buttons for "saved dishes", "your reviewed dishes", and "view tastebudds":
- "your reviewed dishes" links to a new page "reviewed-dishes" showing that user's past reviews in card format
- "saved dishes" goes to "saved-dishes", showing the list in card format
- "view tastebudds" simply links to existing tasteBudds page

Fixed up profile.html page

---

app/templates/tasteProfile.html

now users can only proceed if they've selected a restaurant and dish which exists in the database

fixed autocomplete issue in taste profile setup

---

app/templates/base.html
app/templates/components/feed_card.html
app/templates/dailyDish.html
backend/routes/daily_dish_routes.py
backend/utils.py

infinity scrolls till end of card deck is reached. Could make it load the first cards again when the end is reached but it starts to get really sluggish kind of like reddit if you scroll super duper fast

114 load more cards when end of daily dish is reached

---

app/static/css/TasteBuds.css
app/static/css/dish_detail.css
app/static/css/dishes.css
app/static/css/review.css
app/templates/restaurant_detail.html
app/templates/review.html
backend/routes/dish_routes.py

profanity filter on, back button on review also now works.  Changed a few styling elements like the flash message on dish detail so it doesn't do weird things to the page.

139 put profanity filter on review
